### ISSUE TITLE
Implement retry logic for webhooks

### ISSUE THREAD

**Issue by eepstein** [Ethercast/site#7]
In cases of intermittent target service availability or a temporary outage, having webhooks retried would be a boon.

**Comment by moodysalem** [comment]
You can now contribute to this issue in this repo
https://github.com/Ethercast/ethercast-backend

Here is the code
https://github.com/Ethercast/ethercast-backend/blob/master/src/pipe/send-webhook-request.ts

Creating the issue in that package
